name: Angular Component Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Install Chrome Headless
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Run Component Tests
      working-directory: ./frontend
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x16 &
        npm test -- --watch=false --browsers=ChromeHeadless --include=src/app/components/create-monster/create-monster.component.spec.ts --code-coverage