name: Angular Component Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run Component Tests
      working-directory: ./frontend
      run: |
        npm test --code-coverage --watch=false --browsers=ChromeHeadless --include=src/app/components/create-monster/create-monster.component.spec.ts