name: Angular Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Verify lock file
      run: |
        if [ ! -f package-lock.json ]; then
          npm install --package-lock-only
          git add package-lock.json
        fi

    - name: Cache dependencies
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          node_modules
          .angular/cache
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Run Tests
      run: |
        npm test -- --watch=false --browsers=ChromeHeadless --include=src/app/components/create-monster/create-monster.component.spec.ts